// Chapter 04 · How They Sound — handwritten waveform + voice swatches.
// Each swatch has paired EN + ZH voices; tap plays the sample that matches
// the page's current language.

function HandWave() {
  // wobbly hand-drawn waveform shape
  return (
    <svg viewBox="0 0 600 140" className="hand-wave" aria-hidden="true">
      <path d="M 6 70
               Q 16 70, 22 60 T 38 80 T 56 50 T 74 92 T 96 32
               Q 108 26, 116 70
               T 138 96 T 162 38 T 188 88 T 214 46
               Q 224 44, 232 72
               T 256 90 T 282 50 T 308 84 T 334 38 T 360 76
               Q 372 80, 382 60
               T 410 92 T 436 30 T 462 88 T 488 52 T 514 80 T 540 64 T 574 72 T 596 70"
            stroke="var(--pen-blue)" strokeWidth="1.6" fill="none" strokeLinecap="round" strokeLinejoin="round"/>
      <path d="M 6 70 Q 100 78, 200 66 T 400 74 T 596 70"
            stroke="var(--pen-blue)" strokeWidth="0.8" fill="none" opacity="0.4"/>
    </svg>
  );
}

function PlayGlyph({ playing }) {
  return <span className="play-glyph">{playing ? '❚❚' : '▷'}</span>;
}

function Voice({ lang = 'en' }) {
  // 5 swatches × 2 languages. Audio files are pre-generated by
  // scripts/generate-voice-samples.py.
  const swatches = [
    { tape: 'kraft',  label_en: 'warm · low · slow',  label_zh: '温暖 · 偏低 · 慢',
      en: 'public/voices/warm-en.mp3',     zh: 'public/voices/warm-zh.mp3' },
    { tape: 'pink',   label_en: 'bright · curious',   label_zh: '明亮 · 好奇',
      en: 'public/voices/bright-en.mp3',   zh: 'public/voices/bright-zh.mp3' },
    { tape: 'dotted', label_en: 'quiet · careful',    label_zh: '安静 · 谨慎',
      en: 'public/voices/quiet-en.mp3',    zh: 'public/voices/quiet-zh.mp3' },
    { tape: 'mint',   label_en: 'dry · ironic',       label_zh: '冷淡 · 反讽',
      en: 'public/voices/dry-en.mp3',      zh: 'public/voices/dry-zh.mp3' },
    { tape: 'kraft',  label_en: 'cheerful · bright',  label_zh: '元气 · 明亮',
      en: 'public/voices/cheerful-en.mp3', zh: 'public/voices/cheerful-zh.mp3' },
  ];

  const [playingIdx, setPlayingIdx] = React.useState(-1);
  const audioRef = React.useRef(null);

  const stop = React.useCallback(() => {
    if (audioRef.current) {
      audioRef.current.pause();
      audioRef.current = null;
    }
    setPlayingIdx(-1);
  }, []);

  const play = React.useCallback((i, src) => {
    if (playingIdx === i) { stop(); return; }
    stop();
    const a = new Audio(src);
    audioRef.current = a;
    a.addEventListener('ended', () => { if (audioRef.current === a) stop(); });
    a.addEventListener('error', () => { if (audioRef.current === a) stop(); });
    a.play().catch(() => stop());
    setPlayingIdx(i);
  }, [playingIdx, stop]);

  // Stop playback when language toggles mid-play (avoids ZH voice continuing
  // while the page is in EN mode).
  React.useEffect(() => { stop(); }, [lang, stop]);
  React.useEffect(() => () => { if (audioRef.current) audioRef.current.pause(); }, []);

  return (
    <section className="section voice-section" id="voice" data-screen-label="06 Voice">
      <div className="container">
        <div className="chapter-header center">
          <div className="chapter-mark center">
            <span className="en-only">Chapter 04</span>
            <span className="zh-only">第四章</span>
            <span className="diamond">◆</span>
            <span className="roman en-only">How They Sound</span>
            <span className="roman zh-only">ta 的声音</span>
          </div>
          <h2 className="chapter-title center">
            <span className="en-only">
              Pick a voice that knows how to say <em>your name</em>.
            </span>
            <span className="zh-only">
              挑一个会叫<em>你名字</em>的声音。
            </span>
          </h2>
          <p className="chapter-sub">
            <span className="en-only">
              Every character gets their own voice — picked from a library, locked in, theirs.
              Hear them remember you.
            </span>
            <span className="zh-only">
              每个角色都有自己的声音 —— 从声音库里挑一把,定下来,从此就是 ta 的。听 ta 唤你的名字。
            </span>
          </p>
        </div>

        <div className="voice-spread">
          {/* LEFT — wave page */}
          <div className="voice-page voice-wave-page">
            <div className="page-rule" aria-hidden="true"/>
            <div className="wave-frame">
              <HandWave/>
              <span className="wave-mark wm-1">
                <span className="en-only">(she&rsquo;s laughing here)</span>
                <span className="zh-only">(她在这里笑了)</span>
              </span>
              <span className="wave-mark wm-2">
                <span className="en-only">(this is the long pause)</span>
                <span className="zh-only">(这是那个长长的停顿)</span>
              </span>
              <span className="wave-mark wm-3">
                <span className="en-only">(this is when she calls you)</span>
                <span className="zh-only">(她在这里叫你的名字)</span>
              </span>
            </div>
            <div className="voice-page-tab">
              <span className="en-only">a voice, mapped</span>
              <span className="zh-only">一把声音的样子</span>
            </div>
          </div>

          {/* RIGHT — swatches */}
          <div className="voice-page voice-swatch-page">
            <div className="page-rule" aria-hidden="true"/>
            <div className="voice-swatches">
              {swatches.map((s, i) => (
                <button
                  key={i}
                  className={`voice-swatch tape-${s.tape}${playingIdx === i ? ' playing' : ''}`}
                  type="button"
                  onClick={() => play(i, lang === 'zh' ? s.zh : s.en)}
                  aria-pressed={playingIdx === i}
                >
                  <PlayGlyph playing={playingIdx === i}/>
                  <span className="en-only">{s.label_en}</span>
                  <span className="zh-only">{s.label_zh}</span>
                </button>
              ))}
            </div>
            <div className="voice-margin-note">
              <span className="en-only">tap a label to hear it.</span>
              <span className="zh-only">点一下,听听看。</span>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
window.Voice = Voice;
